/**
 * MQL5 EA templates for strategy export (PROJ-26).
 * Each template uses {{PLACEHOLDER}} syntax filled by the export API route.
 */

export const MT5_TEMPLATES: Record<string, string> = {
  time_range_breakout: `//+------------------------------------------------------------------+
//|  Time-Range Breakout Expert Advisor                              |
//|  Symbol:     {{SYMBOL}}                                          |
//|  Backtest:   {{DATE_FROM}} - {{DATE_TO}}                         |
//|  Exported:   {{EXPORT_DATE}}                                     |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtest Platform"
#property version   "1.00"
#property strict
#property description "Time-Range Breakout | OCO | Risk% Sizing | Trading Day Filter"

#include <Trade\\Trade.mqh>
#include <Trade\\PositionInfo.mqh>
#include <Trade\\OrderInfo.mqh>
#include <Trade\\SymbolInfo.mqh>

//+------------------------------------------------------------------+
enum ENUM_LOT_MODE
{
   LOT_MODE_FIXED    = 0,   // Fixed Lot Size
   LOT_MODE_RISK_PCT = 1    // % Risk per Trade
};

enum ENUM_TIME_MODE
{
   TIME_MODE_DE_PLUS_OFFSET = 0,   // DE-Zeit + Broker-Offset
   TIME_MODE_BROKER_DIRECT  = 1    // Broker-Server-Zeit direkt
};

//+------------------------------------------------------------------+
enum ENUM_LOG_LEVEL
{
   LOG_SILENT  = 0,   // Errors & critical events only
   LOG_NORMAL  = 1,   // + Order events, range, force-close
   LOG_VERBOSE = 2    // + Minute-tick debug inside range window
};

//+------------------------------------------------------------------+
input group "=== Symbol & Magic ==="
input string        InpSymbol              = "{{SYMBOL}}+"; // Symbol at broker (e.g. XAUUSD+, XAUUSDm, XAUUSD.a)
input ulong         InpMagic               = 20260420;     // Magic Number
input string        InpComment             = "TRB";        // Order Comment

input group "=== Timezone ==="
input ENUM_TIME_MODE InpTimeMode           = TIME_MODE_DE_PLUS_OFFSET; // Time mode
input int           InpBrokerOffsetDE      = {{BROKER_OFFSET}}; // Broker time = DE-Zeit + X hours

input group "=== Times (DE-Zeit) ==="
input int           InpRangeStartHour      = {{RANGE_START_H}};  // Range Start Hour
input int           InpRangeStartMin       = {{RANGE_START_M}};  // Range Start Minute
input int           InpRangeEndHour        = {{RANGE_END_H}};    // Range End Hour
input int           InpRangeEndMin         = {{RANGE_END_M}};    // Range End Minute
input int           InpEntryCutoffHour     = {{CUTOFF_H}};       // Entry Cutoff Hour
input int           InpEntryCutoffMin      = {{CUTOFF_M}};       // Entry Cutoff Minute
input int           InpForceCloseHour      = {{CLOSE_H}};        // Force Close Hour
input int           InpForceCloseMin       = {{CLOSE_M}};        // Force Close Minute

input group "=== Trading Days ==="
input bool          InpTradeMonday         = {{TRADE_MON}};
input bool          InpTradeTuesday        = {{TRADE_TUE}};
input bool          InpTradeWednesday      = {{TRADE_WED}};
input bool          InpTradeThursday       = {{TRADE_THU}};
input bool          InpTradeFriday         = {{TRADE_FRI}};

input group "=== Position Sizing ==="
input ENUM_LOT_MODE InpLotMode             = {{LOT_MODE_NAME}};  // Lot Mode
input double        InpFixedLot            = {{FIXED_LOT}};     // Fixed Lot Size
input double        InpRiskPercent         = {{RISK_PERCENT}};  // Risk % per Trade

input group "=== SL / TP (in Points) ==="
input int           InpSL_Points           = {{SL_POINTS}};  // Stop Loss in Points
input int           InpTP_Points           = {{TP_POINTS}};  // Take Profit in Points
input int           InpRangeBufferPts      = 0;              // Buffer on High/Low in Points
input int           InpSlippage            = 30;             // Slippage Points

input group "=== OCO ==="
input bool          InpUseOCO              = true;  // Cancel opposite order when one fills

input group "=== Trailing Stop (Points, 0 = off) ==="
input double        InpTrailTrigger        = {{TRAIL_TRIGGER_PIPS}};
input double        InpTrailLock           = {{TRAIL_LOCK_PIPS}};

input group "=== Logging ==="
input ENUM_LOG_LEVEL InpLogLevel           = LOG_NORMAL;   // Log-Level

//+------------------------------------------------------------------+
CTrade        trade;
CPositionInfo posInfo;
COrderInfo    orderInfo;
CSymbolInfo   symInfo;

int    g_lastProcessedDay = -1;
bool   g_rangeCalculated  = false;
bool   g_ordersPlaced     = false;
bool   g_pendingCleared   = false;
bool   g_forceClosed      = false;
double g_rangeHigh        = 0.0;
double g_rangeLow         = 0.0;
ulong  g_buyStopTicket    = 0;
ulong  g_sellStopTicket   = 0;
int    g_digits           = 0;
double g_point            = 0.0;
string g_symbol           = "";

datetime g_rangeEndBroker    = 0;
datetime g_entryCutoffBroker = 0;
datetime g_forceCloseBroker  = 0;

//+------------------------------------------------------------------+
int OnInit()
{
   g_symbol = InpSymbol;
   if(!SymbolSelect(g_symbol, true))
   {
      PrintFormat("ERROR: Symbol '%s' not available.", g_symbol);
      return(INIT_FAILED);
   }
   if(!symInfo.Name(g_symbol)) return(INIT_FAILED);
   symInfo.RefreshRates();

   g_digits = (int)SymbolInfoInteger(g_symbol, SYMBOL_DIGITS);
   g_point  = SymbolInfoDouble(g_symbol, SYMBOL_POINT);

   trade.SetExpertMagicNumber(InpMagic);
   trade.SetDeviationInPoints(InpSlippage);
   trade.SetTypeFillingBySymbol(g_symbol);

   if(InpLogLevel >= LOG_NORMAL)
   {
      Print("=================================================");
      Print("=== Time-Range Breakout EA ===");
      Print("=================================================");
      PrintFormat("Symbol: %s | Digits: %d | Point: %.5f",
                  g_symbol, g_digits, g_point);
      PrintFormat("Tick Value: %.5f | Tick Size: %.5f | Contract: %.2f",
                  SymbolInfoDouble(g_symbol, SYMBOL_TRADE_TICK_VALUE),
                  SymbolInfoDouble(g_symbol, SYMBOL_TRADE_TICK_SIZE),
                  SymbolInfoDouble(g_symbol, SYMBOL_TRADE_CONTRACT_SIZE));
      PrintFormat("Min Lot: %.2f | Max Lot: %.2f | Lot Step: %.2f",
                  SymbolInfoDouble(g_symbol, SYMBOL_VOLUME_MIN),
                  SymbolInfoDouble(g_symbol, SYMBOL_VOLUME_MAX),
                  SymbolInfoDouble(g_symbol, SYMBOL_VOLUME_STEP));
      PrintFormat("Stop Level: %d Points | Freeze Level: %d Points",
                  (int)SymbolInfoInteger(g_symbol, SYMBOL_TRADE_STOPS_LEVEL),
                  (int)SymbolInfoInteger(g_symbol, SYMBOL_TRADE_FREEZE_LEVEL));
      PrintFormat("Zeit-Modus: %s",
                  InpTimeMode == TIME_MODE_DE_PLUS_OFFSET ? "DE+Offset" : "Broker-Direkt");
      PrintFormat("Zeiten (Input): Range %02d:%02d-%02d:%02d | Cutoff %02d:%02d | Close %02d:%02d",
                  InpRangeStartHour, InpRangeStartMin,
                  InpRangeEndHour, InpRangeEndMin,
                  InpEntryCutoffHour, InpEntryCutoffMin,
                  InpForceCloseHour, InpForceCloseMin);
      if(InpTimeMode == TIME_MODE_DE_PLUS_OFFSET)
         PrintFormat("  -> Broker-Zeit (mit Offset +%dh): Range %02d:%02d-%02d:%02d | Cutoff %02d:%02d | Close %02d:%02d",
                     InpBrokerOffsetDE,
                     (InpRangeStartHour + InpBrokerOffsetDE) % 24, InpRangeStartMin,
                     (InpRangeEndHour   + InpBrokerOffsetDE) % 24, InpRangeEndMin,
                     (InpEntryCutoffHour+ InpBrokerOffsetDE) % 24, InpEntryCutoffMin,
                     (InpForceCloseHour + InpBrokerOffsetDE) % 24, InpForceCloseMin);
      PrintFormat("Sizing: %s | Fix=%.2f | Risk=%.2f%%",
                  InpLotMode == LOT_MODE_FIXED ? "FIXED" : "RISK%",
                  InpFixedLot, InpRiskPercent);
      PrintFormat("SL: %d Points | TP: %d Points", InpSL_Points, InpTP_Points);
      PrintFormat("Account: Balance=%.2f %s | Equity=%.2f | Leverage=1:%d",
                  AccountInfoDouble(ACCOUNT_BALANCE),
                  AccountInfoString(ACCOUNT_CURRENCY),
                  AccountInfoDouble(ACCOUNT_EQUITY),
                  (int)AccountInfoInteger(ACCOUNT_LEVERAGE));
      PrintFormat("TimeCurrent()=%s | TimeGMT()=%s",
                  TimeToString(TimeCurrent(), TIME_DATE|TIME_SECONDS),
                  TimeToString(TimeGMT(),     TIME_DATE|TIME_SECONDS));
      Print("=================================================");
   }
   else
      PrintFormat("EA Init OK | Symbol=%s", g_symbol);
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   PrintFormat("EA stopped. Reason: %d", reason);
}

//+------------------------------------------------------------------+
datetime GetBrokerTimeToday(int inputHour, int inputMin)
{
   MqlDateTime now;
   TimeToStruct(TimeCurrent(), now);

   int brokerHour = inputHour;
   int dayShift = 0;

   if(InpTimeMode == TIME_MODE_DE_PLUS_OFFSET)
   {
      brokerHour = inputHour + InpBrokerOffsetDE;
      while(brokerHour >= 24) { brokerHour -= 24; dayShift++; }
      while(brokerHour <  0)  { brokerHour += 24; dayShift--; }
   }

   MqlDateTime t;
   t.year = now.year;  t.mon = now.mon;  t.day = now.day;
   t.hour = brokerHour; t.min = inputMin; t.sec = 0;

   return StructToTime(t) + dayShift * 86400;
}

//+------------------------------------------------------------------+
bool IsTradingDayAllowed()
{
   MqlDateTime dt;
   TimeToStruct(TimeCurrent(), dt);
   switch(dt.day_of_week)
   {
      case 1: return InpTradeMonday;
      case 2: return InpTradeTuesday;
      case 3: return InpTradeWednesday;
      case 4: return InpTradeThursday;
      case 5: return InpTradeFriday;
      default: return false;
   }
}

//+------------------------------------------------------------------+
void CheckDailyReset()
{
   MqlDateTime dt;
   TimeToStruct(TimeCurrent(), dt);

   if(dt.day != g_lastProcessedDay)
   {
      g_lastProcessedDay = dt.day;
      g_rangeCalculated  = false;
      g_ordersPlaced     = false;
      g_pendingCleared   = false;
      g_forceClosed      = false;
      g_rangeHigh        = 0.0;
      g_rangeLow         = 0.0;
      g_buyStopTicket    = 0;
      g_sellStopTicket   = 0;

      g_rangeEndBroker    = GetBrokerTimeToday(InpRangeEndHour,    InpRangeEndMin);
      g_entryCutoffBroker = GetBrokerTimeToday(InpEntryCutoffHour, InpEntryCutoffMin);
      g_forceCloseBroker  = GetBrokerTimeToday(InpForceCloseHour,  InpForceCloseMin);

      if(InpLogLevel >= LOG_VERBOSE)
      {
         PrintFormat("--- Daily Reset | Now=%s | DoW=%d (%s) | RangeEnd=%s | Cutoff=%s | Close=%s",
                     TimeToString(TimeCurrent(), TIME_DATE|TIME_MINUTES),
                     dt.day_of_week,
                     IsTradingDayAllowed() ? "TRADING" : "SKIP",
                     TimeToString(g_rangeEndBroker,    TIME_DATE|TIME_MINUTES),
                     TimeToString(g_entryCutoffBroker, TIME_DATE|TIME_MINUTES),
                     TimeToString(g_forceCloseBroker,  TIME_DATE|TIME_MINUTES));
      }
   }
}

//+------------------------------------------------------------------+
bool CalculateRange()
{
   datetime rangeStart = GetBrokerTimeToday(InpRangeStartHour, InpRangeStartMin);
   MqlRates rates[];
   ArraySetAsSeries(rates, true);
   int copied = CopyRates(g_symbol, PERIOD_M1, 0, 300, rates);
   if(copied <= 0)
   {
      PrintFormat("CopyRates failed: copied=%d err=%d", copied, GetLastError());
      return false;
   }

   double highest = -DBL_MAX, lowest = DBL_MAX;
   int    matched = 0;
   for(int i = 0; i < copied; i++)
   {
      if(rates[i].time >= rangeStart && rates[i].time < g_rangeEndBroker)
      {
         if(rates[i].high > highest) highest = rates[i].high;
         if(rates[i].low  < lowest)  lowest  = rates[i].low;
         matched++;
      }
   }
   if(matched == 0)
   {
      PrintFormat("Range: no bars in window %s - %s (copied=%d oldest=%s newest=%s)",
                  TimeToString(rangeStart,       TIME_DATE|TIME_MINUTES),
                  TimeToString(g_rangeEndBroker, TIME_DATE|TIME_MINUTES),
                  copied,
                  copied > 0 ? TimeToString(rates[copied-1].time, TIME_DATE|TIME_MINUTES) : "-",
                  copied > 0 ? TimeToString(rates[0].time,        TIME_DATE|TIME_MINUTES) : "-");
      return false;
   }

   g_rangeHigh      = NormalizeDouble(highest + InpRangeBufferPts * g_point, g_digits);
   g_rangeLow       = NormalizeDouble(lowest  - InpRangeBufferPts * g_point, g_digits);
   g_rangeCalculated = true;
   if(InpLogLevel >= LOG_NORMAL)
      PrintFormat("RANGE: High=%.*f Low=%.*f Spread=%.*f Bars=%d",
                  g_digits, g_rangeHigh, g_digits, g_rangeLow,
                  g_digits, g_rangeHigh - g_rangeLow, matched);
   return true;
}

//+------------------------------------------------------------------+
double NormalizeLot(double lot)
{
   double minLot  = SymbolInfoDouble(g_symbol, SYMBOL_VOLUME_MIN);
   double maxLot  = SymbolInfoDouble(g_symbol, SYMBOL_VOLUME_MAX);
   double stepLot = SymbolInfoDouble(g_symbol, SYMBOL_VOLUME_STEP);
   if(lot < minLot)  lot = minLot;
   if(lot > maxLot)  lot = maxLot;
   if(stepLot > 0)   lot = MathFloor(lot / stepLot) * stepLot;
   int digits = (stepLot >= 1.0) ? 0 : (stepLot >= 0.1) ? 1 : 2;
   return NormalizeDouble(lot, digits);
}

//+------------------------------------------------------------------+
double CalculateLotSize(double entryPrice, double slPrice)
{
   if(InpLotMode == LOT_MODE_FIXED)
      return NormalizeLot(InpFixedLot);

   double balance   = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskMoney = balance * InpRiskPercent / 100.0;
   double tickVal   = SymbolInfoDouble(g_symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize  = SymbolInfoDouble(g_symbol, SYMBOL_TRADE_TICK_SIZE);
   if(tickVal <= 0 || tickSize <= 0)
   {
      PrintFormat("Lot fallback: tickVal=%.5f tickSize=%.5f", tickVal, tickSize);
      return NormalizeLot(InpFixedLot);
   }
   double slDist = MathAbs(entryPrice - slPrice);
   if(slDist <= 0) return NormalizeLot(InpFixedLot);

   double lossPerLot = (slDist / tickSize) * tickVal;
   if(lossPerLot <= 0) return NormalizeLot(InpFixedLot);

   double lot = riskMoney / lossPerLot;
   lot = NormalizeLot(lot);

   if(InpLogLevel >= LOG_NORMAL)
      PrintFormat("  Risk-Calc: Balance=%.2f Risk%%=%.2f -> %.2f %s | SL-Dist=%.*f | Loss/Lot=%.2f -> Lot=%.2f",
                  balance, InpRiskPercent, riskMoney,
                  AccountInfoString(ACCOUNT_CURRENCY),
                  g_digits, slDist, lossPerLot, lot);
   return lot;
}

//+------------------------------------------------------------------+
bool PlacePendingOrders()
{
   symInfo.RefreshRates();
   double ask     = symInfo.Ask();
   double bid     = symInfo.Bid();
   int    stopLvl = (int)SymbolInfoInteger(g_symbol, SYMBOL_TRADE_STOPS_LEVEL);
   double minDist = stopLvl * g_point;

   double buyPrice = g_rangeHigh;
   if(minDist > 0 && buyPrice - ask < minDist)
      buyPrice = NormalizeDouble(ask + minDist + g_point, g_digits);
   double buySL  = NormalizeDouble(buyPrice - InpSL_Points * g_point, g_digits);
   double buyTP  = NormalizeDouble(buyPrice + InpTP_Points * g_point, g_digits);
   double buyLot = CalculateLotSize(buyPrice, buySL);
   bool buyOk = trade.BuyStop(buyLot, buyPrice, g_symbol, buySL, buyTP, ORDER_TIME_DAY, 0, InpComment + "_BS");
   if(buyOk)
   {
      g_buyStopTicket = trade.ResultOrder();
      if(InpLogLevel >= LOG_NORMAL)
         PrintFormat("BuyStop #%I64u Lot=%.2f @%.*f SL=%.*f TP=%.*f",
                     g_buyStopTicket, buyLot, g_digits, buyPrice, g_digits, buySL, g_digits, buyTP);
   }
   else
      PrintFormat("BuyStop FAILED: rc=%u (%s) | Lot=%.2f @%.*f SL=%.*f TP=%.*f | Ask=%.*f",
                  trade.ResultRetcode(), trade.ResultRetcodeDescription(),
                  buyLot, g_digits, buyPrice, g_digits, buySL, g_digits, buyTP, g_digits, ask);

   double sellPrice = g_rangeLow;
   if(minDist > 0 && bid - sellPrice < minDist)
      sellPrice = NormalizeDouble(bid - minDist - g_point, g_digits);
   double sellSL  = NormalizeDouble(sellPrice + InpSL_Points * g_point, g_digits);
   double sellTP  = NormalizeDouble(sellPrice - InpTP_Points * g_point, g_digits);
   double sellLot = CalculateLotSize(sellPrice, sellSL);
   bool sellOk = trade.SellStop(sellLot, sellPrice, g_symbol, sellSL, sellTP, ORDER_TIME_DAY, 0, InpComment + "_SS");
   if(sellOk)
   {
      g_sellStopTicket = trade.ResultOrder();
      if(InpLogLevel >= LOG_NORMAL)
         PrintFormat("SellStop #%I64u Lot=%.2f @%.*f SL=%.*f TP=%.*f",
                     g_sellStopTicket, sellLot, g_digits, sellPrice, g_digits, sellSL, g_digits, sellTP);
   }
   else
      PrintFormat("SellStop FAILED: rc=%u (%s) | Lot=%.2f @%.*f SL=%.*f TP=%.*f | Bid=%.*f",
                  trade.ResultRetcode(), trade.ResultRetcodeDescription(),
                  sellLot, g_digits, sellPrice, g_digits, sellSL, g_digits, sellTP, g_digits, bid);

   g_ordersPlaced = (buyOk && sellOk);
   return g_ordersPlaced;
}

//+------------------------------------------------------------------+
void HandleOCO()
{
   if(!InpUseOCO) return;
   if(g_buyStopTicket == 0 && g_sellStopTicket == 0) return;

   bool buyPos = false, sellPos = false, buyPend = false, sellPend = false;

   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(!posInfo.SelectByIndex(i)) continue;
      if(posInfo.Magic() != InpMagic || posInfo.Symbol() != g_symbol) continue;
      if(posInfo.PositionType() == POSITION_TYPE_BUY)  buyPos  = true;
      if(posInfo.PositionType() == POSITION_TYPE_SELL) sellPos = true;
   }
   for(int i = OrdersTotal() - 1; i >= 0; i--)
   {
      if(!orderInfo.SelectByIndex(i)) continue;
      if(orderInfo.Magic() != InpMagic || orderInfo.Symbol() != g_symbol) continue;
      if(orderInfo.Ticket() == g_buyStopTicket)  buyPend  = true;
      if(orderInfo.Ticket() == g_sellStopTicket) sellPend = true;
   }

   if(buyPos && sellPend && g_sellStopTicket > 0)
   {
      if(trade.OrderDelete(g_sellStopTicket))
      { if(InpLogLevel >= LOG_NORMAL) PrintFormat("OCO: Buy filled -> SellStop #%I64u deleted", g_sellStopTicket); g_sellStopTicket = 0; }
   }
   if(sellPos && buyPend && g_buyStopTicket > 0)
   {
      if(trade.OrderDelete(g_buyStopTicket))
      { if(InpLogLevel >= LOG_NORMAL) PrintFormat("OCO: Sell filled -> BuyStop #%I64u deleted", g_buyStopTicket); g_buyStopTicket = 0; }
   }
}

//+------------------------------------------------------------------+
void ManageTrail()
{
   if(InpTrailTrigger <= 0 || InpTrailLock <= 0) return;
   symInfo.RefreshRates();
   double trigger  = InpTrailTrigger * g_point;
   double lockDist = InpTrailLock    * g_point;

   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(!posInfo.SelectByIndex(i)) continue;
      if(posInfo.Magic() != InpMagic || posInfo.Symbol() != g_symbol) continue;
      ulong  ticket = posInfo.Ticket();
      double open   = posInfo.PriceOpen();
      double sl     = posInfo.StopLoss();
      double tp     = posInfo.TakeProfit();

      if(posInfo.PositionType() == POSITION_TYPE_BUY)
      {
         double bid = symInfo.Bid();
         if(bid - open >= trigger)
         {
            double newSL = NormalizeDouble(bid - lockDist, g_digits);
            if(newSL > sl) trade.PositionModify(ticket, newSL, tp);
         }
      }
      else if(posInfo.PositionType() == POSITION_TYPE_SELL)
      {
         double ask = symInfo.Ask();
         if(open - ask >= trigger)
         {
            double newSL = NormalizeDouble(ask + lockDist, g_digits);
            if(sl == 0 || newSL < sl) trade.PositionModify(ticket, newSL, tp);
         }
      }
   }
}

//+------------------------------------------------------------------+
void DeleteOurPendingOrders(string reason)
{
   for(int i = OrdersTotal() - 1; i >= 0; i--)
   {
      if(!orderInfo.SelectByIndex(i)) continue;
      if(orderInfo.Magic() != InpMagic || orderInfo.Symbol() != g_symbol) continue;
      ulong t = orderInfo.Ticket();
      if(trade.OrderDelete(t))
      {
         if(InpLogLevel >= LOG_NORMAL)
            PrintFormat("Pending #%I64u deleted (%s)", t, reason);
      }
   }
   g_buyStopTicket = 0; g_sellStopTicket = 0;
}

//+------------------------------------------------------------------+
void CloseAllOurPositions(string reason)
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(!posInfo.SelectByIndex(i)) continue;
      if(posInfo.Magic() != InpMagic || posInfo.Symbol() != g_symbol) continue;
      ulong t = posInfo.Ticket();
      if(trade.PositionClose(t))
      {
         if(InpLogLevel >= LOG_NORMAL)
            PrintFormat("Position #%I64u closed (%s)", t, reason);
      }
      else
         PrintFormat("Close #%I64u FAILED: %s", t, trade.ResultRetcodeDescription());
   }
}

//+------------------------------------------------------------------+
void OnTick()
{
   CheckDailyReset();
   datetime now = TimeCurrent();

   if(!g_forceClosed && now >= g_forceCloseBroker)
   {
      CloseAllOurPositions("ForceClose");
      DeleteOurPendingOrders("ForceClose");
      g_forceClosed = true;
      return;
   }

   if(!IsTradingDayAllowed()) return;

   if(now >= g_entryCutoffBroker)
   {
      if(!g_pendingCleared) { DeleteOurPendingOrders("EntryCutoff"); g_pendingCleared = true; }
      HandleOCO();
      ManageTrail();
      return;
   }

   if(!g_rangeCalculated && now >= g_rangeEndBroker)
      CalculateRange();

   if(g_rangeCalculated && !g_ordersPlaced && now < g_entryCutoffBroker)
      PlacePendingOrders();

   HandleOCO();
   ManageTrail();
}
`,

  moving_average_crossover: `//+------------------------------------------------------------------+
//|  Moving Average Crossover Expert Advisor                         |
//|  Strategy:   moving_average_crossover                            |
//|  Symbol:     {{SYMBOL}}                                          |
//|  Backtest:   {{DATE_FROM}} - {{DATE_TO}}                         |
//|  Exported:   {{EXPORT_DATE}}                                     |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtest Platform"
#property version   "1.00"

#include <Trade\\Trade.mqh>

//--- Inputs
input int      InpFastPeriod     = {{FAST_PERIOD}};  // Fast MA Period
input int      InpSlowPeriod     = {{SLOW_PERIOD}};  // Slow MA Period
input double   InpStopLossPips   = {{STOP_LOSS}};    // Stop Loss (Pips)
input double   InpTakeProfitPips = {{TAKE_PROFIT}};  // Take Profit (Pips, 0 = Signal-Exit only)
input string   InpDirection      = "{{DIRECTION}}";  // Direction: long | short | both
input double   InpLotSize        = 0.01;             // Lot Size
input ulong    InpMagicNumber    = 88002;            // Magic Number

//--- Globals
CTrade  Trade;
int     gFastHandle;
int     gSlowHandle;
double  gPipSize;

//+------------------------------------------------------------------+
int OnInit()
{
   Trade.SetExpertMagicNumber(InpMagicNumber);
   gPipSize    = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   if(_Digits == 5 || _Digits == 3) gPipSize *= 10.0;
   gFastHandle = iMA(_Symbol, PERIOD_CURRENT, InpFastPeriod, 0, MODE_SMA, PRICE_CLOSE);
   gSlowHandle = iMA(_Symbol, PERIOD_CURRENT, InpSlowPeriod, 0, MODE_SMA, PRICE_CLOSE);
   if(gFastHandle == INVALID_HANDLE || gSlowHandle == INVALID_HANDLE) return(INIT_FAILED);
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   IndicatorRelease(gFastHandle);
   IndicatorRelease(gSlowHandle);
}

//+------------------------------------------------------------------+
void OnTick()
{
   // Act only on new bar
   static datetime lastBar = 0;
   datetime curBar = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(curBar == lastBar) return;
   lastBar = curBar;

   double fast[], slow[];
   ArraySetAsSeries(fast, true);
   ArraySetAsSeries(slow, true);
   if(CopyBuffer(gFastHandle, 0, 0, 3, fast) < 3) return;
   if(CopyBuffer(gSlowHandle, 0, 0, 3, slow) < 3) return;

   // Crossover detection (bar[1] = completed previous bar, bar[2] = bar before that)
   bool bullCross = (fast[2] <= slow[2]) && (fast[1] > slow[1]);
   bool bearCross = (fast[2] >= slow[2]) && (fast[1] < slow[1]);

   double sl  = InpStopLossPips   * gPipSize;
   double tp  = InpTakeProfitPips * gPipSize;
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

   if(bullCross)
   {
      if(HasPosition(POSITION_TYPE_SELL)) CloseAll();
      if((InpDirection == "long" || InpDirection == "both") && !HasPosition(POSITION_TYPE_BUY))
      {
         double tpPrice = tp > 0 ? NormalizeDouble(ask + tp, _Digits) : 0;
         Trade.Buy(InpLotSize, _Symbol, ask,
                   NormalizeDouble(ask - sl, _Digits), tpPrice, "MA Long");
      }
   }

   if(bearCross)
   {
      if(HasPosition(POSITION_TYPE_BUY)) CloseAll();
      if((InpDirection == "short" || InpDirection == "both") && !HasPosition(POSITION_TYPE_SELL))
      {
         double tpPrice = tp > 0 ? NormalizeDouble(bid - tp, _Digits) : 0;
         Trade.Sell(InpLotSize, _Symbol, bid,
                    NormalizeDouble(bid + sl, _Digits), tpPrice, "MA Short");
      }
   }
}

//+------------------------------------------------------------------+
bool HasPosition(ENUM_POSITION_TYPE type)
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if((ulong)PositionGetInteger(POSITION_MAGIC) == InpMagicNumber &&
         (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) == type)
         return true;
   }
   return false;
}

//+------------------------------------------------------------------+
void CloseAll()
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if((ulong)PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
         Trade.PositionClose(ticket);
   }
}
`,

  rsi_threshold: `//+------------------------------------------------------------------+
//|  RSI Threshold Expert Advisor                                    |
//|  Strategy:   rsi_threshold                                       |
//|  Symbol:     {{SYMBOL}}                                          |
//|  Backtest:   {{DATE_FROM}} - {{DATE_TO}}                         |
//|  Exported:   {{EXPORT_DATE}}                                     |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtest Platform"
#property version   "1.00"

#include <Trade\\Trade.mqh>

//--- Inputs
input int      InpRsiPeriod       = {{RSI_PERIOD}};       // RSI Period
input double   InpOversoldLevel   = {{OVERSOLD_LEVEL}};   // Oversold Level
input double   InpOverboughtLevel = {{OVERBOUGHT_LEVEL}}; // Overbought Level
input double   InpStopLossPips    = {{STOP_LOSS}};        // Stop Loss (Pips)
input double   InpTakeProfitPips  = {{TAKE_PROFIT}};      // Take Profit (Pips, 0 = Signal-Exit only)
input string   InpDirection       = "{{DIRECTION}}";      // Direction: long | short | both
input double   InpLotSize         = 0.01;                 // Lot Size
input ulong    InpMagicNumber     = 88003;                // Magic Number

//--- Globals
CTrade  Trade;
int     gRsiHandle;
double  gPipSize;

//+------------------------------------------------------------------+
int OnInit()
{
   Trade.SetExpertMagicNumber(InpMagicNumber);
   gPipSize   = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   if(_Digits == 5 || _Digits == 3) gPipSize *= 10.0;
   gRsiHandle = iRSI(_Symbol, PERIOD_CURRENT, InpRsiPeriod, PRICE_CLOSE);
   if(gRsiHandle == INVALID_HANDLE) return(INIT_FAILED);
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   IndicatorRelease(gRsiHandle);
}

//+------------------------------------------------------------------+
void OnTick()
{
   // Act only on new bar
   static datetime lastBar = 0;
   datetime curBar = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(curBar == lastBar) return;
   lastBar = curBar;

   double rsi[];
   ArraySetAsSeries(rsi, true);
   if(CopyBuffer(gRsiHandle, 0, 0, 3, rsi) < 3) return;

   // Level-cross detection (bar[1] = completed previous bar, bar[2] = bar before that)
   bool longSignal  = (rsi[2] < InpOversoldLevel)    && (rsi[1] >= InpOversoldLevel);
   bool shortSignal = (rsi[2] > InpOverboughtLevel)  && (rsi[1] <= InpOverboughtLevel);

   double sl  = InpStopLossPips   * gPipSize;
   double tp  = InpTakeProfitPips * gPipSize;
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

   if(longSignal)
   {
      if(HasPosition(POSITION_TYPE_SELL)) CloseAll();
      if((InpDirection == "long" || InpDirection == "both") && !HasPosition(POSITION_TYPE_BUY))
      {
         double tpPrice = tp > 0 ? NormalizeDouble(ask + tp, _Digits) : 0;
         Trade.Buy(InpLotSize, _Symbol, ask,
                   NormalizeDouble(ask - sl, _Digits), tpPrice, "RSI Long");
      }
   }

   if(shortSignal)
   {
      if(HasPosition(POSITION_TYPE_BUY)) CloseAll();
      if((InpDirection == "short" || InpDirection == "both") && !HasPosition(POSITION_TYPE_SELL))
      {
         double tpPrice = tp > 0 ? NormalizeDouble(bid - tp, _Digits) : 0;
         Trade.Sell(InpLotSize, _Symbol, bid,
                    NormalizeDouble(bid + sl, _Digits), tpPrice, "RSI Short");
      }
   }
}

//+------------------------------------------------------------------+
bool HasPosition(ENUM_POSITION_TYPE type)
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if((ulong)PositionGetInteger(POSITION_MAGIC) == InpMagicNumber &&
         (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) == type)
         return true;
   }
   return false;
}

//+------------------------------------------------------------------+
void CloseAll()
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if((ulong)PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
         Trade.PositionClose(ticket);
   }
}
`,
};

export const SUPPORTED_STRATEGIES = Object.keys(MT5_TEMPLATES);
