/**
 * MQL5 EA templates for strategy export (PROJ-26).
 * Each template uses {{PLACEHOLDER}} syntax filled by the export API route.
 */

export const MT5_TEMPLATES: Record<string, string> = {
  time_range_breakout: `//+------------------------------------------------------------------+
//|  Time-Range Breakout Expert Advisor                              |
//|  Strategy:   time_range_breakout                                 |
//|  Symbol:     {{SYMBOL}}                                          |
//|  Backtest:   {{DATE_FROM}} - {{DATE_TO}}                         |
//|  Exported:   {{EXPORT_DATE}}                                     |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtest Platform"
#property version   "1.00"

#include <Trade\\Trade.mqh>

//--- Inputs
input string   InpRangeStart       = "{{RANGE_START}}";      // Range Start (HH:MM)
input string   InpRangeEnd         = "{{RANGE_END}}";        // Range End (HH:MM)
input string   InpTriggerDeadline  = "{{TRIGGER_DEADLINE}}"; // Trigger Deadline (HH:MM)
input string   InpTimeExit         = "{{TIME_EXIT}}";        // Force Close (HH:MM)
input double   InpStopLossPips     = {{STOP_LOSS}};          // Stop Loss (Pips)
input double   InpTakeProfitPips   = {{TAKE_PROFIT}};        // Take Profit (Pips)
input string   InpDirection        = "{{DIRECTION}}";        // Direction: long | short | both
input int      InpEntryDelayBars   = {{ENTRY_DELAY_BARS}};   // Entry Delay (bars after range close)
input double   InpTrailTriggerPips = {{TRAIL_TRIGGER_PIPS}}; // Trail Trigger Pips (0 = off)
input double   InpTrailLockPips    = {{TRAIL_LOCK_PIPS}};    // Trail Lock Pips
input double   InpLotSize          = 0.01;                   // Lot Size
input ulong    InpMagicNumber      = 88001;                  // Magic Number

//--- Globals
CTrade   Trade;
double   gPipSize;
double   gRangeHigh;
double   gRangeLow;
bool     gRangeBuilt;
string   gLastDate;

//+------------------------------------------------------------------+
int OnInit()
{
   Trade.SetExpertMagicNumber(InpMagicNumber);
   gPipSize    = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   if(_Digits == 5 || _Digits == 3) gPipSize *= 10.0;
   gRangeHigh  = 0;
   gRangeLow   = DBL_MAX;
   gRangeBuilt = false;
   gLastDate   = "";
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
void OnDeinit(const int reason) {}

//+------------------------------------------------------------------+
void OnTick()
{
   MqlDateTime dt;
   TimeToStruct(TimeCurrent(), dt);
   string today = StringFormat("%04d.%02d.%02d", dt.year, dt.mon, dt.day);

   // --- Reset state on new trading day
   if(today != gLastDate)
   {
      gLastDate   = today;
      gRangeHigh  = 0;
      gRangeLow   = DBL_MAX;
      gRangeBuilt = false;
   }

   int hhmm = dt.hour * 100 + dt.min;
   int rsInt = ParseHHMM(InpRangeStart);
   int reInt = ParseHHMM(InpRangeEnd);
   int tdInt = ParseHHMM(InpTriggerDeadline);
   int teInt = ParseHHMM(InpTimeExit);

   // --- Force-close all and cancel pending at TimeExit
   if(hhmm >= teInt)
   {
      CloseAll();
      CancelPending();
      return;
   }

   // --- Build range: track H/L within [RangeStart, RangeEnd)
   if(hhmm >= rsInt && hhmm < reInt)
   {
      double mid = (SymbolInfoDouble(_Symbol, SYMBOL_ASK) + SymbolInfoDouble(_Symbol, SYMBOL_BID)) * 0.5;
      if(mid > gRangeHigh) gRangeHigh = mid;
      if(mid < gRangeLow)  gRangeLow  = mid;
      return;
   }

   // --- Place OCO stop orders once after RangeEnd (until TriggerDeadline)
   if(hhmm >= reInt && hhmm < tdInt && !gRangeBuilt && gRangeHigh > 0 && gRangeLow < DBL_MAX)
   {
      gRangeBuilt = true;
      double sl  = InpStopLossPips   * gPipSize;
      double tp  = InpTakeProfitPips * gPipSize;

      if(InpDirection == "long" || InpDirection == "both")
      {
         double entry = NormalizeDouble(gRangeHigh, _Digits);
         Trade.BuyStop(InpLotSize, entry,
                       NormalizeDouble(entry - sl, _Digits),
                       NormalizeDouble(entry + tp, _Digits),
                       "TRB Long", ORDER_TIME_DAY, 0);
      }
      if(InpDirection == "short" || InpDirection == "both")
      {
         double entry = NormalizeDouble(gRangeLow, _Digits);
         Trade.SellStop(InpLotSize, entry,
                        NormalizeDouble(entry + sl, _Digits),
                        NormalizeDouble(entry - tp, _Digits),
                        "TRB Short", ORDER_TIME_DAY, 0);
      }
      return;
   }

   // --- Cancel pending after TriggerDeadline
   if(hhmm >= tdInt) CancelPending();

   // --- Trailing stop
   if(InpTrailTriggerPips > 0 && InpTrailLockPips > 0) ManageTrail();
}

//+------------------------------------------------------------------+
void ManageTrail()
{
   double trigger = InpTrailTriggerPips * gPipSize;
   double lock    = InpTrailLockPips    * gPipSize;

   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if((ulong)PositionGetInteger(POSITION_MAGIC) != InpMagicNumber) continue;

      double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
      double currentSL = PositionGetDouble(POSITION_SL);
      double currentTP = PositionGetDouble(POSITION_TP);

      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY)
      {
         double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
         if(bid - openPrice >= trigger)
         {
            double newSL = NormalizeDouble(bid - lock, _Digits);
            if(newSL > currentSL)
               Trade.PositionModify(ticket, newSL, currentTP);
         }
      }
      else if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_SELL)
      {
         double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
         if(openPrice - ask >= trigger)
         {
            double newSL = NormalizeDouble(ask + lock, _Digits);
            if(currentSL == 0 || newSL < currentSL)
               Trade.PositionModify(ticket, newSL, currentTP);
         }
      }
   }
}

//+------------------------------------------------------------------+
void CloseAll()
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if((ulong)PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
         Trade.PositionClose(ticket);
   }
}

//+------------------------------------------------------------------+
void CancelPending()
{
   for(int i = OrdersTotal() - 1; i >= 0; i--)
   {
      ulong ticket = OrderGetTicket(i);
      if(ticket == 0) continue;
      if((ulong)OrderGetInteger(ORDER_MAGIC) == InpMagicNumber)
         Trade.OrderDelete(ticket);
   }
}

//+------------------------------------------------------------------+
int ParseHHMM(const string hhMM)
{
   string parts[];
   StringSplit(hhMM, ':', parts);
   if(ArraySize(parts) < 2) return 0;
   return (int)StringToInteger(parts[0]) * 100 + (int)StringToInteger(parts[1]);
}
`,

  moving_average_crossover: `//+------------------------------------------------------------------+
//|  Moving Average Crossover Expert Advisor                         |
//|  Strategy:   moving_average_crossover                            |
//|  Symbol:     {{SYMBOL}}                                          |
//|  Backtest:   {{DATE_FROM}} - {{DATE_TO}}                         |
//|  Exported:   {{EXPORT_DATE}}                                     |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtest Platform"
#property version   "1.00"

#include <Trade\\Trade.mqh>

//--- Inputs
input int      InpFastPeriod     = {{FAST_PERIOD}};  // Fast MA Period
input int      InpSlowPeriod     = {{SLOW_PERIOD}};  // Slow MA Period
input double   InpStopLossPips   = {{STOP_LOSS}};    // Stop Loss (Pips)
input double   InpTakeProfitPips = {{TAKE_PROFIT}};  // Take Profit (Pips, 0 = Signal-Exit only)
input string   InpDirection      = "{{DIRECTION}}";  // Direction: long | short | both
input double   InpLotSize        = 0.01;             // Lot Size
input ulong    InpMagicNumber    = 88002;            // Magic Number

//--- Globals
CTrade  Trade;
int     gFastHandle;
int     gSlowHandle;
double  gPipSize;

//+------------------------------------------------------------------+
int OnInit()
{
   Trade.SetExpertMagicNumber(InpMagicNumber);
   gPipSize    = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   if(_Digits == 5 || _Digits == 3) gPipSize *= 10.0;
   gFastHandle = iMA(_Symbol, PERIOD_CURRENT, InpFastPeriod, 0, MODE_SMA, PRICE_CLOSE);
   gSlowHandle = iMA(_Symbol, PERIOD_CURRENT, InpSlowPeriod, 0, MODE_SMA, PRICE_CLOSE);
   if(gFastHandle == INVALID_HANDLE || gSlowHandle == INVALID_HANDLE) return(INIT_FAILED);
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   IndicatorRelease(gFastHandle);
   IndicatorRelease(gSlowHandle);
}

//+------------------------------------------------------------------+
void OnTick()
{
   // Act only on new bar
   static datetime lastBar = 0;
   datetime curBar = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(curBar == lastBar) return;
   lastBar = curBar;

   double fast[], slow[];
   ArraySetAsSeries(fast, true);
   ArraySetAsSeries(slow, true);
   if(CopyBuffer(gFastHandle, 0, 0, 3, fast) < 3) return;
   if(CopyBuffer(gSlowHandle, 0, 0, 3, slow) < 3) return;

   // Crossover detection (bar[1] = completed previous bar, bar[2] = bar before that)
   bool bullCross = (fast[2] <= slow[2]) && (fast[1] > slow[1]);
   bool bearCross = (fast[2] >= slow[2]) && (fast[1] < slow[1]);

   double sl  = InpStopLossPips   * gPipSize;
   double tp  = InpTakeProfitPips * gPipSize;
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

   if(bullCross)
   {
      if(HasPosition(POSITION_TYPE_SELL)) CloseAll();
      if((InpDirection == "long" || InpDirection == "both") && !HasPosition(POSITION_TYPE_BUY))
      {
         double tpPrice = tp > 0 ? NormalizeDouble(ask + tp, _Digits) : 0;
         Trade.Buy(InpLotSize, _Symbol, ask,
                   NormalizeDouble(ask - sl, _Digits), tpPrice, "MA Long");
      }
   }

   if(bearCross)
   {
      if(HasPosition(POSITION_TYPE_BUY)) CloseAll();
      if((InpDirection == "short" || InpDirection == "both") && !HasPosition(POSITION_TYPE_SELL))
      {
         double tpPrice = tp > 0 ? NormalizeDouble(bid - tp, _Digits) : 0;
         Trade.Sell(InpLotSize, _Symbol, bid,
                    NormalizeDouble(bid + sl, _Digits), tpPrice, "MA Short");
      }
   }
}

//+------------------------------------------------------------------+
bool HasPosition(ENUM_POSITION_TYPE type)
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if((ulong)PositionGetInteger(POSITION_MAGIC) == InpMagicNumber &&
         (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) == type)
         return true;
   }
   return false;
}

//+------------------------------------------------------------------+
void CloseAll()
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if((ulong)PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
         Trade.PositionClose(ticket);
   }
}
`,

  rsi_threshold: `//+------------------------------------------------------------------+
//|  RSI Threshold Expert Advisor                                    |
//|  Strategy:   rsi_threshold                                       |
//|  Symbol:     {{SYMBOL}}                                          |
//|  Backtest:   {{DATE_FROM}} - {{DATE_TO}}                         |
//|  Exported:   {{EXPORT_DATE}}                                     |
//+------------------------------------------------------------------+
#property copyright "Generated by Backtest Platform"
#property version   "1.00"

#include <Trade\\Trade.mqh>

//--- Inputs
input int      InpRsiPeriod       = {{RSI_PERIOD}};       // RSI Period
input double   InpOversoldLevel   = {{OVERSOLD_LEVEL}};   // Oversold Level
input double   InpOverboughtLevel = {{OVERBOUGHT_LEVEL}}; // Overbought Level
input double   InpStopLossPips    = {{STOP_LOSS}};        // Stop Loss (Pips)
input double   InpTakeProfitPips  = {{TAKE_PROFIT}};      // Take Profit (Pips, 0 = Signal-Exit only)
input string   InpDirection       = "{{DIRECTION}}";      // Direction: long | short | both
input double   InpLotSize         = 0.01;                 // Lot Size
input ulong    InpMagicNumber     = 88003;                // Magic Number

//--- Globals
CTrade  Trade;
int     gRsiHandle;
double  gPipSize;

//+------------------------------------------------------------------+
int OnInit()
{
   Trade.SetExpertMagicNumber(InpMagicNumber);
   gPipSize   = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   if(_Digits == 5 || _Digits == 3) gPipSize *= 10.0;
   gRsiHandle = iRSI(_Symbol, PERIOD_CURRENT, InpRsiPeriod, PRICE_CLOSE);
   if(gRsiHandle == INVALID_HANDLE) return(INIT_FAILED);
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   IndicatorRelease(gRsiHandle);
}

//+------------------------------------------------------------------+
void OnTick()
{
   // Act only on new bar
   static datetime lastBar = 0;
   datetime curBar = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(curBar == lastBar) return;
   lastBar = curBar;

   double rsi[];
   ArraySetAsSeries(rsi, true);
   if(CopyBuffer(gRsiHandle, 0, 0, 3, rsi) < 3) return;

   // Level-cross detection (bar[1] = completed previous bar, bar[2] = bar before that)
   bool longSignal  = (rsi[2] < InpOversoldLevel)    && (rsi[1] >= InpOversoldLevel);
   bool shortSignal = (rsi[2] > InpOverboughtLevel)  && (rsi[1] <= InpOverboughtLevel);

   double sl  = InpStopLossPips   * gPipSize;
   double tp  = InpTakeProfitPips * gPipSize;
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

   if(longSignal)
   {
      if(HasPosition(POSITION_TYPE_SELL)) CloseAll();
      if((InpDirection == "long" || InpDirection == "both") && !HasPosition(POSITION_TYPE_BUY))
      {
         double tpPrice = tp > 0 ? NormalizeDouble(ask + tp, _Digits) : 0;
         Trade.Buy(InpLotSize, _Symbol, ask,
                   NormalizeDouble(ask - sl, _Digits), tpPrice, "RSI Long");
      }
   }

   if(shortSignal)
   {
      if(HasPosition(POSITION_TYPE_BUY)) CloseAll();
      if((InpDirection == "short" || InpDirection == "both") && !HasPosition(POSITION_TYPE_SELL))
      {
         double tpPrice = tp > 0 ? NormalizeDouble(bid - tp, _Digits) : 0;
         Trade.Sell(InpLotSize, _Symbol, bid,
                    NormalizeDouble(bid + sl, _Digits), tpPrice, "RSI Short");
      }
   }
}

//+------------------------------------------------------------------+
bool HasPosition(ENUM_POSITION_TYPE type)
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if((ulong)PositionGetInteger(POSITION_MAGIC) == InpMagicNumber &&
         (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) == type)
         return true;
   }
   return false;
}

//+------------------------------------------------------------------+
void CloseAll()
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if((ulong)PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
         Trade.PositionClose(ticket);
   }
}
`,
};

export const SUPPORTED_STRATEGIES = Object.keys(MT5_TEMPLATES);
